# This is a basic workflow to help you get started with Actions

name: Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up dependencies
        run: sudo apt install npm && npm i -g eslint

      # Runs a set of commands using the runners shell
      - name: Set up development enviroment
        run: |
          npm install
          cd tabs
          npm install
          cd ..

      - name: Test the project
        run: |
          cd tabs
          npm run test
          cd ..
        # Run the lint.
      
      - name: Lint the project
        run: npm run lint

